version: '3.1'

volumes:
  npm:

services:

  web:
    build: .
    command: yarn serve
    volumes:
      - .:/usr/src/app
      - npm:/usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      API_URL: http://backend.test/graphql
