var path = require('path')
const PrerenderSPAPlugin = require('prerender-spa-plugin')
const Renderer = PrerenderSPAPlugin.PuppeteerRenderer
const CompressionPlugin = require('compression-webpack-plugin');
const CompressionLevel = 5

module.exports = {
  productionSourceMap: false,
  pluginOptions: {
    s3Deploy: {}
  },

  devServer: {
    disableHostCheck: true
  },

  css: {
    loaderOptions: {
      sass: {
        data: `
          @import "@/assets/styles/main.scss";
        `
      }
    }
  },
  configureWebpack: {
    devtool: 'sourcemaps',
    module: {
      rules: [
        {
          test: /\.font\.js/,
          use: [
            'style-loader',
            'css-loader',
            'webfonts-loader'
          ]
        }
      ]
    }
  }
}

if (process.env.NODE_ENV === 'production') {
  module.exports.configureWebpack.plugins = (module.exports.configureWebpack.plugins || []).concat([
    new PrerenderSPAPlugin({
      staticDir: path.join(__dirname, 'dist'),
      outputDir: path.join(__dirname, 'prerendered'),
      routes: [
        // Static pages
        // '/',
        // '/page-not-found',
        // '/esports',
        // '/sports',
        // '/live-casino',
        // '/casino',
        // '/casino/providers',
        // '/casino/search',
        // '/live-casino/search',
        // '/support',
        // '/support/contact-us',
        // '/support/terms-and-conditions',
        // '/support/betting-rules',
        // '/support/privacy-policy',
        // '/support/cookie-policy',
        // '/support/faq',
        // '/about',
        // '/about/about-arcanebet',
        // '/promotions',
        // '/promotions/welcome-offer-sport',
        // '/promotions/welcome-offer-casino',
        // '/promotions/bonus-rules',
        // '/responsible-gaming',
        // '/responsible-gaming/introduction',
        // '/responsible-gaming/limits',

        // // Titles
        // '/esports/call-of-duty',
        // '/esports/counter-strike',
        // '/esports/crossfire',
        // '/esports/dota-2',
        // '/esports/e-sport',
        // '/esports/e-sport-apex-legends',
        // '/esports/e-sport-arena-of-valor',
        // '/esports/e-sport-artifact',
        // '/esports/e-sport-clash-royale',
        // '/esports/e-sport-dragon-ball-fighter-z',
        // '/esports/e-sport-fifa',
        // '/esports/e-sport-gears-of-war',
        // '/esports/e-sport-king-of-glory',
        // '/esports/e-sport-madden-nfl',
        // '/esports/e-sport-nba2-k',
        // '/esports/e-sport-paladins',
        // '/esports/e-sport-player-unknowns-battlegrounds',
        // '/esports/e-sport-pro-evolution-soccer',
        // '/esports/e-sport-quake',
        // '/esports/e-sport-ssbm',
        // '/esports/e-sport-tekken',
        // '/esports/e-sport-tf2',
        // '/esports/e-sport-world-of-warcraft',
        // '/esports/equestrian',
        // '/esports/esport-auto-chess',
        // '/esports/esport-brawl-stars',
        // '/esports/esport-dota-underlords',
        // '/esports/esport-fighting-games',
        // '/esports/esport-fortnite',
        // '/esports/esport-teamfight-tactics',
        // '/esports/halo',
        // '/esports/hearthstone',
        // '/esports/heroes-of-the-storm',
        // '/esports/league-of-legends',
        // '/esports/overwatch',
        // '/esports/rainbow-six',
        // '/esports/rocket-league',
        // '/esports/smite',
        // '/esports/star-craft',
        // '/esports/street-fighter-v',
        // '/esports/vainglory',
        // '/esports/war-craft-iii',
        // '/esports/world-of-tanks',
        // '/sports/7-ball-run',
        // '/sports/alpine-skiing',
        // '/sports/american-football',
        // '/sports/aquatics',
        // '/sports/archery',
        // '/sports/athletics',
        // '/sports/aussie-rules',
        // '/sports/badminton',
        // '/sports/bandy',
        // '/sports/baseball',
        // '/sports/basketball',
        // '/sports/basketball-3x3',
        // '/sports/basque-pelota',
        // '/sports/beach-handball',
        // '/sports/beach-soccer',
        // '/sports/beach-tennis',
        // '/sports/beach-volley',
        // '/sports/biathlon',
        // '/sports/bikes',
        // '/sports/bmx-racing',
        // '/sports/bobsleigh',
        // '/sports/bowls',
        // '/sports/boxing',
        // '/sports/canoe-slalom',
        // '/sports/canoeing',
        // '/sports/chess',
        // '/sports/cricket',
        // '/sports/cross-country',
        // '/sports/curling',
        // '/sports/cycling',
        // '/sports/cycling-cycle-ball',
        // '/sports/darts',
        // '/sports/diving',
        // '/sports/drag-racing',
        // '/sports/dtm',
        // '/sports/esport-mtg',
        // '/sports/fencing',
        // '/sports/field-hockey',
        // '/sports/figure-skating',
        // '/sports/finnish-baseball',
        // '/sports/fishing',
        // '/sports/floorball',
        // '/sports/formula-1',
        // '/sports/formula-e',
        // '/sports/freestyle',
        // '/sports/freestyle-skiing',
        // '/sports/futsal',
        // '/sports/gaelic-football',
        // '/sports/gaelic-hurling',
        // '/sports/gaelic-sports',
        // '/sports/golf',
        // '/sports/greyhound',
        // '/sports/gymnastics',
        // '/sports/handball',
        // '/sports/horse-racing',
        // '/sports/horseball',
        // '/sports/ice-hockey',
        // '/sports/indoor-soccer',
        // '/sports/indy-lights',
        // '/sports/indycar',
        // '/sports/inline-hockey',
        // '/sports/judo',
        // '/sports/kabaddi',
        // '/sports/lacrosse',
        // '/sports/luge',
        // '/sports/mma',
        // '/sports/modern-pentathlon',
        // '/sports/modified-racing',
        // '/sports/moto-gp',
        // '/sports/moto2',
        // '/sports/moto3',
        // '/sports/motocross',
        // '/sports/motorsport',
        // '/sports/mountain-bike',
        // '/sports/nascar',
        // '/sports/netball',
        // '/sports/nordic-combined',
        // '/sports/off-road',
        // '/sports/olympics',
        // '/sports/olympics-youth',
        // '/sports/padel-tennis',
        // '/sports/pesapallo',
        // '/sports/petanque',
        // '/sports/polo',
        // '/sports/pool',
        // '/sports/rally',
        // '/sports/rhythmic-gymnastics',
        // '/sports/riding',
        // '/sports/rink-hockey',
        // '/sports/rowing',
        // '/sports/rugby',
        // '/sports/rugby-league',
        // '/sports/sailing',
        // '/sports/sc',
        // '/sports/schwingen',
        // '/sports/sepak-takraw',
        // '/sports/shooting',
        // '/sports/short-track',
        // '/sports/skeleton',
        // '/sports/ski-jumping',
        // '/sports/snooker',
        // '/sports/snowboard',
        // '/sports/snowboardcross-parallel',
        // '/sports/soccer',
        // '/sports/soccer-mythical',
        // '/sports/softball',
        // '/sports/specials',
        // '/sports/speed-boat-racing',
        // '/sports/speed-skating',
        // '/sports/speedway',
        // '/sports/sprint-car-racing',
        // '/sports/squash',
        // '/sports/stock-car-racing',
        // '/sports/streethockey',
        // '/sports/sumo',
        // '/sports/superbike',
        // '/sports/surfing',
        // '/sports/swimming',
        // '/sports/synchronized-swimming',
        // '/sports/table-tennis',
        // '/sports/taekwondo',
        // '/sports/tennis',
        // '/sports/track-cycling',
        // '/sports/trampolining',
        // '/sports/triathlon',
        // '/sports/trotting',
        // '/sports/truck-tractor-pulling',
        // '/sports/volleyball',
        // '/sports/waterpolo',
        // '/sports/weightlifting',
        // '/sports/winter-sports',
        // '/sports/world-championship',
        // '/sports/world-lottery',
        // '/sports/wrestling',
        //
        // // Casino categories
        // '/casino/favorites',
        // '/casino/golden-oldies',
        // '/casino/jackpots',
        // '/casino/new',
        // '/casino/slots',
        // '/casino/table-games',
        // '/live-casino/blackjack',
        // '/live-casino/hot-tables',
        // '/live-casino/other-tables',
        // '/live-casino/poker',
        // '/live-casino/roulette',
        //
        // // Casino content providers and vendors
        // '/casino/providers/bet-on-finance',
        // '/casino/providers/hybrino',
        // "/casino/providers/play'n-go",
        // '/casino/providers/aristocrats',
        // '/casino/providers/cryptologic',
        // '/casino/providers/i-gaming2-go',
        // '/casino/providers/sigma-gaming',
        // '/casino/providers/2-by2',
        // '/casino/providers/btg',
        // '/casino/providers/parlay',
        // '/casino/providers/felt-gaming',
        // '/casino/providers/bb-tech',
        // '/casino/providers/magnet-gaming',
        // '/casino/providers/live-games',
        // '/casino/providers/game-os-opus',
        // '/casino/providers/mgs-opus',
        // '/casino/providers/pragmatic-opus',
        // '/casino/providers/microgaming-ttg',
        // '/casino/providers/booming-ttg',
        // '/casino/providers/pragmatic-ttg',
        // '/casino/providers/playson-ttg',
        // '/casino/providers/poker-plus',
        // '/casino/providers/e-bet',
        // '/casino/providers/side-city',
        // '/casino/providers/igtnt',
        // '/casino/providers/odds-matrix2',
        // '/casino/providers/amaya',
        // '/casino/providers/saber-interactive',
        // '/casino/providers/instant-click',
        // '/casino/providers/cgs',
        // '/casino/providers/gameway',
        // '/casino/providers/kalamba',
        // '/casino/providers/games-warehouse',
        // '/casino/providers/probability-jones',
        // '/casino/providers/magic-dreams',
        // '/casino/providers/spieldev',
        // '/casino/providers/storm-games',
        // '/casino/providers/sunfox-games',
        // '/casino/providers/live5-gaming',
        // '/casino/providers/reel-time-gaming',
        // '/casino/providers/gameart',
        // '/casino/providers/jftw',
        // '/casino/providers/zonelock',
        // '/casino/providers/adopt-it-publishing',
        // '/casino/providers/bla-bla-bla-studios',
        // '/casino/providers/fantasma-games',
        // '/casino/providers/touchstone',
        // '/casino/providers/meta-gu',
        // '/casino/providers/pear-fiction',
        // '/casino/providers/wild-streak',
        // '/casino/providers/yoloplay',
        // '/casino/providers/amatic',
        // '/casino/providers/rabcat',
        // '/casino/providers/tombala',
        // '/casino/providers/entwine',
        // '/casino/providers/mutuel-play',
        // '/casino/providers/concept-gaming',
        // '/casino/providers/asylum-labs',
        // '/casino/providers/red-rake',
        // '/casino/providers/colossus-bets',
        // '/casino/providers/slingshot',
        // '/casino/providers/wikibetting',
        // '/casino/providers/old-skool',
        // '/casino/providers/skillzz-gaming',
        // '/casino/providers/triple-edge-studios',
        // '/casino/providers/wagermill',
        // '/casino/providers/genesis-gaming',
        // '/casino/providers/pragmatic-live',
        // '/casino/providers/fortune-factory',
        // '/casino/providers/givme',
        // '/casino/providers/red-tiger-gaming',
        // '/casino/providers/microgaming',
        // '/casino/providers/igt',
        // '/casino/providers/x-pro-gaming',
        // '/casino/providers/bet-soft',
        // '/casino/providers/green-tube',
        // '/casino/providers/omi',
        // '/casino/providers/evolution-gaming',
        // '/casino/providers/nyx-gaming',
        // '/casino/providers/i-soft-bet',
        // '/casino/providers/ezugi',
        // '/casino/providers/bet-games',
        // '/casino/providers/vivo',
        // '/casino/providers/one-x-two-gaming',
        // '/casino/providers/williams',
        // '/casino/providers/egt',
        // '/casino/providers/egb',
        // '/casino/providers/leander-games',
        // '/casino/providers/poker-klas',
        // '/casino/providers/quickspin',
        // '/casino/providers/spigo',
        // '/casino/providers/genii',
        // '/casino/providers/lucky-streak',
        // '/casino/providers/authentic',
        // '/casino/providers/playson',
        // '/casino/providers/habanero',
        // '/casino/providers/igrosoft',
        // '/casino/providers/mr-slotty',
        // '/casino/providers/pari-play',
        // '/casino/providers/stakelogic',
        // '/casino/providers/join-games',
        // '/casino/providers/booming-games',
        // '/casino/providers/spinomenal',
        // '/casino/providers/endorphina',
        // '/casino/providers/multi-slot',
        // '/casino/providers/yggdrasil',
        // '/casino/providers/lega',
        // '/casino/providers/sthlm-gaming',
        // '/casino/providers/dice-lab',
        // '/casino/providers/golden-hero',
        // '/casino/providers/blueprint-gaming',
        // '/casino/providers/high5-games',
        // '/casino/providers/kambi',
        // '/casino/providers/bee-fee',
        // '/casino/providers/realistic',
        // '/casino/providers/ainsworth',
        // '/casino/providers/lightning-box',
        // '/casino/providers/leap-gaming',
        // '/casino/providers/iron-dog-studio',
        // '/casino/providers/foxium',
        // '/casino/providers/side-city',
        // '/casino/providers/big-time-gaming',
        // '/casino/providers/chance-interactive',
        // '/casino/providers/next-gen',
        // '/casino/providers/elk',
        // '/casino/providers/asia-gaming',
        // '/casino/providers/booongo',
        // '/casino/providers/betixon',
        // '/casino/providers/extreme-live-gaming',
        // '/casino/providers/eyecon',
        // '/casino/providers/fugaso',
        // '/casino/providers/gamevy',
        // '/casino/providers/gamomat',
        // '/casino/providers/global-bet',
        // '/casino/providers/golden-race',
        // '/casino/providers/ion',
        // '/casino/providers/i-soft-gaming',
        // '/casino/providers/kiron',
        // '/casino/providers/media-live-casino',
        // '/casino/providers/net-ent',
        // '/casino/providers/nolimit-city',
        // '/casino/providers/opus-gaming',
        // '/casino/providers/oriental-gaming',
        // '/casino/providers/oryx',
        // '/casino/providers/platipus',
        // '/casino/providers/play-star',
        // '/casino/providers/portomaso',
        // '/casino/providers/pragmatic-play',
        // '/casino/providers/push-gaming',
        // '/casino/providers/rct',
        // '/casino/providers/reel-nrg',
        // '/casino/providers/relax-gaming',
        // '/casino/providers/spade-gaming',
        // '/casino/providers/synot',
        // '/casino/providers/thunderkick',
        // '/casino/providers/tom-horn2',
        // '/casino/providers/tom-horn',
        // '/casino/providers/ttg',
        // '/casino/providers/vi-g',
        // '/casino/providers/wazdan',
        // '/casino/providers/crazy-tooth',
        // '/casino/providers/fuga-gaming',
        // '/casino/providers/bullet-proof',
        // '/casino/providers/gig-games',
        // '/casino/providers/merkur',
        // '/casino/providers/switch-studios',
        // '/casino/providers/sg',
        // '/casino/providers/sapphire-gaming',
        // '/casino/providers/in-touch-games',
        // '/casino/providers/electric-elephant',
        // '/casino/providers/one-touch',
        // '/casino/providers/play-tech-games-link',
        // '/casino/providers/stormcraft-studios',
        // '/casino/providers/red7',
        // '/casino/providers/bb-games',
        // '/casino/providers/play-tech',
        // '/casino/providers/barcrest',
        // '/casino/providers/mga',
        // '/casino/providers/hacksaw-gaming',
        // '/casino/providers/jade-rabbit-studios',
        // '/casino/providers/cayetano-gaming',
        // '/casino/providers/pulse8',
        // '/casino/providers/gameburger-studios',
        // '/casino/providers/casino-technology',
        // '/casino/providers/ka-gaming',
        // '/casino/providers/max-win-gaming',
        // '/casino/providers/fazi',
        // '/casino/providers/atomic-spin',
        // '/casino/providers/bet-solutions',
        // '/casino/providers/charismatic',
        // '/casino/providers/shuffle',
        // '/casino/providers/revolver-gaming',
        // '/casino/providers/skywind',
        // '/casino/providers/golden-rock-studios',
        // '/casino/providers/all41-studios',
        // '/casino/providers/gaming1',
        // '/casino/providers/swintt',
        // '/casino/providers/northern-lights',
        // '/casino/providers/4-the-player',
        // '/casino/providers/spribe',
        // '/casino/providers/n-soft',
        // '/casino/providers/spearhead-studios',
        // '/casino/providers/d-tech',
        // '/casino/providers/neon-valley-studios',
        // '/casino/providers/neon-valley-studios',
        // '/casino/providers/reel-play',
        // '/casino/providers/pg-soft',
        // '/casino/providers/bet-games',
        // '/casino/providers/gamevy',
        // '/casino/providers/playson',
        // '/casino/providers/net-ent',
        // '/casino/providers/bet-soft',
        // '/casino/providers/oryx-gaming',
        // '/casino/providers/pariplay',
        // '/casino/providers/relax-gaming',
        // '/casino/providers/evolution-gaming',
        // '/casino/providers/elk-gaming',
        // '/casino/providers/spigo',
        // '/casino/providers/quick-spin',
        // '/casino/providers/blueprint',
        // '/casino/providers/red-tiger-gaming',
        // '/casino/providers/bee-fee',
        // '/casino/providers/pragmatic-play',
        // '/casino/providers/microgaming',
        // '/casino/providers/egt'
      ],
      renderer: new Renderer({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
        renderAfterDocumentEvent: 'render-event',
        maxConcurrentRoutes: 2,
        consoleHandler: (route, handler) => {
          let progressMarkers = [
            '/',
            '/esports/call-of-duty',
            '/sports/7-ball-run',
            '/casino/favorites',
            '/live-casino/blackjack',
            '/casino/providers/bet-on-finance'
          ]

          if (progressMarkers.includes(route)) {
            console.log(route, handler.text())
          }
        }
      })
    }),
    new CompressionPlugin({
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      test: /\.(js|css|html)$/,
      compressionOptions: { level: CompressionLevel },
      minRatio: 0.8 // default
    })
  ])
}
