export const ACTIVE_STATUS = 'active'
export const INACTIVE_STATUS = 'inactive'
export const SUSPENDED_STATUS = 'suspended'
export const SETTLED_STATUS = 'settled'
export const CANCELLED_STATUS = 'cancelled'
export const HANDED_OVER_STATUS = 'handed_over'
